services:
  user_service:
    build: ./user-microservice
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./user-microservice/:/app/
    ports:
      - 8002:8000
    environment:
      - DATABASE_URI=postgresql://postgres:postgres@main_db/postgres

  people_service:
    build: ./people-microservice
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./people-microservice/:/app/
    ports:
      - 8001:8000
    environment:
      - DATABASE_URI=postgresql://postgres:postgres@main_db/postgres
      - USERS_SERVICE_HOST_URL=http://user_service:8002

  main_db:
    image: postgres:16.9-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

volumes:
  postgres_data:
