services:
  user_service:
    build: ./user-microservice
    volumes:
      - ./user-microservice/:/app/
    ports:
      - 8002:8000
    env_file:
      - .env
    depends_on:
      - main_db
    networks:
      - microservice_network

  people_service:
    build: ./people-microservice
    volumes:
      - ./people-microservice/:/app/
    ports:
      - 8001:8000
    env_file:
      - .env
    depends_on:
      - main_db
    networks:
      - microservice_network

  main_db:
    image: postgres:16.9-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    networks:
      - microservice_network

  nginx:
    image: nginx:latest
    ports:
      - 8080:8080
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - user_service
      - people_service
    networks:
      - microservice_network

volumes:
  postgres_data:


networks:
  microservice_network:
    driver: bridge
